modLoader = "javafml"
loaderVersion = "[40,)"
issueTrackerURL = "${mod_issues_url}"
license = "${copyright_licence}"

[[mods]]
modId = "mapsync"
version = "${mod_version}"
displayName = "MapSync"
description = "${mod_description}"
displayURL = "${mod_home_url}"
authors = "Gjum,Protonull"
#logoFile = ""

[[dependencies.mapsync]]
modId = "forge"
mandatory = true
versionRange = "[40,)"
ordering = "NONE"
side = "CLIENT"

[[dependencies.mapsync]]
modId = "minecraft"
mandatory = true
versionRange = "[${minecraft_version},)"
ordering = "NONE"
side = "CLIENT"
